<div class="text-xl text-admin-primary">
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
    <p>Admin home</p>
</div>
